### ISSUE TITLE
Can't access the Windows Update Client Website

### ISSUE THREAD

**Issue by CrazyComputer2008** [ExplodingBottle/JMagicProxy#2]
Hello again! Now I have been used the proxy for a while. But now a new problem happened. I can't access the website with the proxy.
The client cannot access [http://windowsupdate.microsoft.com](url),and Microsoft Update returns me 0x800B0001.  Here is the server log.(Maybe the proxy cannot get windowsupdate.microsoft.com and c.microsoft.com's address?)
PS:I have opened WSUS but I don't think that wouldbe a problem.(JRE Version:8u381)
[log1691074820544.txt](https://github.com/ExplodingBottle/JMagicProxy/files/12252302/log1691074820544.txt)

**Comment by ExplodingBottle** [comment]
Hello there,
According to the proxy's log, the issue is related to the DNS. 

2023/08/03 23:03:06 [WARN](io.github.explodingbottle.jmagicproxy.socketopener.SocketOpeningTool): Failed to get IPs of an unknown host.
java.net.UnknownHostException: windowsupdate.microsoft.com
	at java.net.InetAddress.getAllByName0(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at io.github.explodingbottle.jmagicproxy.socketopener.SocketOpeningTool.run(SocketOpeningTool.java:80)
	at io.github.explodingbottle.jmagicproxy.proxy.ConnectionDirectiveHandler.openSocket(ConnectionDirectiveHandler.java:234)
	at io.github.explodingbottle.jmagicproxy.proxy.SocketHandlerThread.handleLineRead(SocketHandlerThread.java:170)
	at io.github.explodingbottle.jmagicproxy.proxy.SocketHandlerThread.run(SocketHandlerThread.java:206)

It says that it is unable to find the requested site. Maybe you could check your DNS or change them.

**Comment by ExplodingBottle** [comment]
Also, on my side with my DNS I am able to reach the website.

**Comment by CrazyComputer2008** [comment]
I have fixed up the [windowsupdate.microsoft.com](url)'s dns problem by adding the IP address(20.72.235.82) on my dns server. But the program seems like still missing [c.microsoft.com](url)'s address. But I can't found the IP use nslookup with google dns.
[log1691243560289.txt](https://github.com/ExplodingBottle/JMagicProxy/files/12267412/log1691243560289.txt)

**Comment by CrazyComputer2008** [comment]
> I have fixed up the [windowsupdate.microsoft.com](url)'s dns problem by adding the IP address(20.72.235.82) on my dns server. But the program seems like still missing [c.microsoft.com](url)'s address. But I can't found the IP use nslookup with google dns. [log1691243560289.txt](https://github.com/ExplodingBottle/JMagicProxy/files/12267412/log1691243560289.txt)

By the way, the website returns me 0x800B0001,which related to a connection issue.(Maybe)

**Comment by ExplodingBottle** [comment]
Hello there,
The c.microsoft.com site is a telemetry website that is no longer reachable, but it is not a problem for the updating.
Could you please attach the Windows Update log file ?

**Comment by CrazyComputer2008** [comment]
OK,here is the log.
PS:I have enabled WSUS.
[WindowsUpdate.log](https://github.com/ExplodingBottle/JMagicProxy/files/12269963/WindowsUpdate.log)

**Comment by ExplodingBottle** [comment]
Hello,
I'm sorry but the problem seems to come from your WSUS server and not from my proxy.
Also, there is something more important: The version of your update agent is 7.6.7600.256, which is bad because this version will always do certificate checks. For this reason, without WSUS, you cannot use my proxy with this version (I really need to document this !)

Here are the steps for removing it:
Download the version for your architecture:
http://download.windowsupdate.com/windowsupdate/redist/standalone/7.4.7600.226/windowsupdateagent30-x86.exe
http://download.windowsupdate.com/windowsupdate/redist/standalone/7.4.7600.226/windowsupdateagent30-x64.exe
http://download.windowsupdate.com/windowsupdate/redist/standalone/7.4.7600.226/windowsupdateagent30-ia64.exe

Then run it with the /uninstall flag

Restart your computer and then install it using the executable you just downloaded

WARNING: If you let the WSUS, Windows Update will automatically update itself again to the wrong version.

If your plan is really to use WSUS then avoid using the proxy which is not faulty in our current case.

Have a nice day

**Comment by CrazyComputer2008** [comment]
OK,I l got it. Now I will use it for the clients without WSUS. Thank you for your help!
